### PR TITLE
download page: Update quality dashboard links, and update "Nightly" to "Preview"

### PR DESCRIPTION
**Pull request by jcfr**
See https://discourse.slicer.org/t/different-dashboard-for-master-and-stable-builds/2091

### CODE REVIEW

**Comment by jcfr** [comment]
@mhalle Would it be possible to integrate this ? 

Corresponding changes have also been integrated in Slicer as [r26928](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26928)

Cc: @pieper @lassoan

**Comment by mhalle** [comment]
I’m in the middle of moving downloads to a new host. I’m also converting to python3 and adopting new geolocation and user agent detection frameworks.

 I’’ll merge in the change when I’m done.

I’ll be out next week, and I don’t want to cut over before I leave and cause a crisis.  I’ll cut over when I’m back.

—Mike

**Comment by jcfr** [comment]
> python3 and adopting new geolocation and user agent detection frameworks.

That is awesome. 

Would be great to learn more about it and leverage this for the Girder based version of the extension manager we are working on.

See  https://github.com/girder/slicer-extension-manager  

Note that in the future it will most likely be renamed to `slicer-package-manager` and also used to manage Slicer packages  (cc: @Pierre-Assemat)

**Comment by pieper** [comment]
@mhalle can you have another look at this?  If you don't have time to maintain this can you add admins and/or move it to the Slicer organization?

**Review by mhalle — CHANGES_REQUESTED** [review]
This pull request doesn't look complete (doesn't do what it says it does).  The diff is just renaming Nightly to Preview.  Is that what you meant?

**Comment by lassoan** [comment]
Yes, indeed, it only updates the release name.

It would be nice if you could merge this pull request and then also change the dashboard link from:

    <li><a href="http://slicer.cdash.org/index.php?project=Slicer4">Quality dashboard</a></li>

to

    <li>Quality dashboard: <a href="http://slicer.cdash.org/index.php?project=Slicer4">stable</a>, <a href="http://slicer.cdash.org/index.php?project=SlicerPreview">preview</a></li>

Thank you!

**Comment by mhalle** [comment]
Just checking, was this diff somewhere that didn’t show up?  It corresponds to the title of the issue, but wasn’t in the issue.  You don’t need to add it now, just wondering.

**Comment by jcfr** [comment]
Link updated. Here is how it would look:

image

**Comment by jcfr** [comment]
> Just checking, was this diff somewhere that didn’t show up?

Thanks for the review and good catch. The PR has been updated to also include update of the dashboard links.

@mhalle Let me know if you need anything else to move forward with this. Thanks

**Comment by jcfr** [comment]
Thanks @mhalle  :smile:

**Pull request merged**
