### PR TITLE
GetBuildInfo: Allow module to be executed

### PR DESCRIPTION
**Pull request by jcfr**
The following is now possible:

```
$ python -m slicer4GetBuildInfo
usage is: /home/jcfr/Projects/slicer4-download/slicer4GetBuildInfo/__main__.py <dbfile>
```

### CODE REVIEW

**Comment by mhalle** [comment]
No need to do this.  `__main__.py` allows the module to be executed without -m:

```
$ python slicer4GetBuildInfo
usage is: slicer4GetBuildInfo <dbfile>
```

which is cleaner to me. Also, slicer4GetBuildInfo isn't really a module, so I think an `__init__.py` confuses things.

**Comment by jcfr** [comment]
Was just following python best practice. 

This one of the first step toward having a pip installable `slicer4-download` where GetBuildInfo (or similar name) would be one of the "executable" provided. In that case, it is relevant to have this structure. It allows to define "entrypoint" in your setup.py. For example of entrypoint, see [here](https://github.com/scikit-build/cmake-python-distributions/blob/b83b34177efdaeda5a3ccffc54a86c436b29570c/setup.py#L43-L47).

**Comment by mhalle** [comment]
GetBuildInfo wasn’t envisioned as a module. It’s a special purpose helper executable. pip installability isn’t a requirement.  If it were module-ized, making the **init**.py file would be the least of the changes required. The code would have to be refactored out of **main**.py.  It would also have to be more library-like, as opposed to main() like.

Perhaps the code should have been that way from first commit, but it isn’t :)

**Comment by jcfr** [comment]
Sounds good. Thanks for spending the time reviewing.

**Comment by mhalle** [comment]
You too.

**Pull request closed without merging**
